---
abstract: Exactly what you're expecting...
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
keywords:
  - MSN
  - client
  - MSNP21
  - IM
  - instant
  - message
  - Windows
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-MSN
provides:
  AnyEvent::MSN:
    file: lib/AnyEvent/MSN.pm
    version: 0.001
  AnyEvent::MSN::Protocol:
    file: lib/AnyEvent/MSN/Protocol.pm
    version: 0.001
requires:
  AnyEvent: 5.31
  AnyEvent::HTTP: 2.1
  Crypt::CBC: 2.30
  Crypt::DES: 2.05
  Crypt::DES_EDE3: 0.01
  Digest::HMAC: 1.02
  Digest::MD5: 2.51
  Digest::SHA: 5.61
  MIME::Base64: 3.13
  Moose: 2.0002
  Try::Tiny: 0.09
  XML::Twig: 3.38
  perl: 5.012
resources:
  bugtracker: http://github.com/sanko/anyevent-msn/issues
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/anyevent-msn.git
  x_ChangeLog: http://github.com/sanko/anyevent-msn/commits
version: 0.001
